default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

development:
  <<: *default
  database: glp1_ecommerce_development

test:
  <<: *default
  database: glp1_ecommerce_test

production:
  <<: *default
  database: glp1_ecommerce_production
  url: <%= ENV['DATABASE_URL'] %>